### PR TITLE
Fix C# blob trigger path

### LINKED ISSUE #166: Default path for C# blob trigger is incorrect
If you create a blob trigger with all default values, the path in the generated BlobTrigger.cs file will look like this: 'sample-workitems/{name}/{name}'

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**
Fixes #166

### CODE REVIEW

File: src/commands/createFunction/CSharpFunctionCreator.ts [hunk 1]
```diff
@@ -59,6 +59,11 @@ export class CSharpFunctionCreator extends FunctionCreatorBase {
                 parameter = 'Path';
             }
 
+            // https://github.com/Microsoft/vscode-azurefunctions/issues/166
+            if (userSettings[key].endsWith('/{name}')) {
```
Comment (StephenWeatherford) [inline src/commands/createFunction/CSharpFunctionCreator.ts]: Would be better to create a const for '/{name}' and use .length
