### PR TITLE
Fix no activity log when deleting containerized function app

### LINKED ISSUE #4004: There is no activity log in the "AZURE" window when deleting a containerized function app
**OS:** All
**Build Version:** 20240229.2
**Regression:** Not a Regression

**Repro Steps:**
1. Delete a containerized function app.
2. Check whether there is an activity log in the "AZURE" window.

**Expect:**
There is an activity log in the "AZURE" window, like the one when deleting a regular function app.
image

**Actual:**
There is no activity log in the "AZURE" window.

**More Info:**
This issue does not reproduce for regular function app.

### PR DESCRIPTION
**Pull request by motm32**
Fixes #4004. 

Can't reuse the deleteSite steps within the appservice tools package since we cannot create a client the same way.

### CODE REVIEW

File: src/tree/containerizedFunctionApp/ResolvedContainerizedFunctionAppResource.ts [hunk 1]
```diff
@@ -139,18 +141,24 @@ export class ResolvedContainerizedFunctionAppResource extends ResolvedFunctionAp
...
-        const deleting: string = localize('DeletingFunctionApp', 'Deleting function app "{0}"...', this.site.name);
-        const deleteSucceeded: string = localize('DeleteFunctionAppSucceeded', 'Successfully deleted function app "{0}".', this.site.name);
-        await context.ui.showWarningMessage(message, { modal: true, stepName: 'confirmDelete' }, DialogResponses.deleteResponse);
-        await window.withProgress({ location: ProgressLocation.Notification, title: deleting }, async (): Promise<void> => {
-            ext.outputChannel.appendLog(deleting);
-            const client = await createWebSiteClient([context, proxyTree.subscription]);
-            await client.webApps.delete(nonNullValueAndProp(this.site, 'resourceGroup'), nonNullValueAndProp(this.site, 'name'));
-            void window.showInformationMessage(deleteSucceeded);
-            ext.outputChannel.appendLog(deleteSucceeded);
+        const title: string = localize('DeleteFunctionApp', 'Delete function app');
```
Comment (MicroFish91) [inline src/tree/containerizedFunctionApp/ResolvedContainerizedFunctionAppResource.ts:151]: I think it might look nice to add the app name to the activity title here here :)

File: src/tree/containerizedFunctionApp/ResolvedContainerizedFunctionAppResource.ts [hunk 2]
```diff
@@ -139,18 +141,24 @@ export class ResolvedContainerizedFunctionAppResource extends ResolvedFunctionAp
...
+
+        const wizard = new AzureWizard(wizardContext, {
+            promptSteps: [new DeleteConfirmationStep(message)],
+            executeSteps: [new DeleteContainerizedFunctionappStep()],
+            title
         });
+
+        await wizard.prompt();
+        await wizard.execute();
+
```
Comment (MicroFish91) [inline src/tree/containerizedFunctionApp/ResolvedContainerizedFunctionAppResource.ts:161]: Nit: Extra new line

File: src/commands/deleteContainerizedFunctionApp/DeleteContainerizedFunctionAppStep.ts [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+import { type DeleteFunctionappWizardContext } from "./DeleteFunctionAppWizardContext";
+
+export class DeleteContainerizedFunctionappStep extends AzureWizardExecuteStep<DeleteFunctionappWizardContext> {
+    public priority: number = 100;
+
+    public async execute(context: DeleteFunctionappWizardContext): Promise<void> {
+        const deleting: string = localize('DeletingFunctionApp', 'Deleting function app "{0}"...', context.site.name);
+        const deleteSucceeded: string = localize('DeleteFunctionAppSucceeded', 'Successfully deleted function app "{0}".', context.site.name);
+
+        await window.withProgress({ location: ProgressLocation.Notification, title: deleting }, async (): Promise<void> => {
```
Comment (MicroFish91) [inline src/commands/deleteContainerizedFunctionApp/DeleteContainerizedFunctionAppStep.ts:20]: Question, can we skip showing this `withProgress` since we already have the live update showing in the activity log?

**Review by MicroFish91 — APPROVED** [review]
Mostly nits, otherwise LGTM

File: src/commands/deleteContainerizedFunctionApp/DeleteFunctionAppWizardContext.ts [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+*  Licensed under the MIT License. See License.md in the project root for license information.
+*--------------------------------------------------------------------------------------------*/
+
+import { type Site } from "@azure/arm-appservice";
+import { type ExecuteActivityContext, type IActionContext } from "@microsoft/vscode-azext-utils";
+import { type ContainerTreeItem } from "../../tree/containerizedFunctionApp/ContainerTreeItem";
+
+export interface DeleteFunctionappWizardContext extends IActionContext, ExecuteActivityContext {
+    site: Site;
+    proxyTree: ContainerTreeItem;
```
Comment (MicroFish91) [inline src/commands/deleteContainerizedFunctionApp/DeleteFunctionAppWizardContext.ts:12]: Actually one other thing, is the only reason we have the proxyTree on the context for the subscription?  If so, maybe you can just build an `ISubscriptionActionContext` at the beginning so you don't have to store the whole tree item reference on the context.

File: src/commands/deleteContainerizedFunctionApp/DeleteContainerizedFunctionAppStep.ts (hunk 3 above)
Comment (nturinski) [reply src/commands/deleteContainerizedFunctionApp/DeleteContainerizedFunctionAppStep.ts:20]: Yeah, I think so. It should be our pattern going forward-- maybe a notification that says:
`Deleting function "{0}". To check progress, view Azure Activity Log.` with a button to take them there?

Comment (MicroFish91) [reply src/commands/deleteContainerizedFunctionApp/DeleteContainerizedFunctionAppStep.ts:20]: Double check me on this, but it seems like anytime the activity log is activated through the wizard, the activity log pane automatically gets focus so it'd probably be hard for the user to miss.

Comment (MicroFish91) [reply src/commands/deleteContainerizedFunctionApp/DeleteContainerizedFunctionAppStep.ts:20]: Oh, you mean tree item description, nevermind, yeah that makes perfect sense.

Comment (nturinski) [reply src/commands/deleteContainerizedFunctionApp/DeleteContainerizedFunctionAppStep.ts:20]: Actually, I didn't realize that the Azure activity log was already focused whenever something happened there so maybe just disregard what I said.

The tree item description might be a bit too verbose to show it there.

File: src/commands/deleteContainerizedFunctionApp/DeleteFunctionAppWizardContext.ts (hunk 4 above)
Comment (motm32) [reply src/commands/deleteContainerizedFunctionApp/DeleteFunctionAppWizardContext.ts]: I don't think I can do this since the I don't have access to the `AzureSubscription` either but I made some changes and put the subscription in the constructor so I could reuse it. Let me know if that's better/worse.

File: src/commands/deleteContainerizedFunctionApp/DeleteFunctionAppWizardContext.ts [hunk 5]
```diff
@@ -0,0 +1,11 @@
+/*---------------------------------------------------------------------------------------------
+*  Copyright (c) Microsoft Corporation. All rights reserved.
+*  Licensed under the MIT License. See License.md in the project root for license information.
+*--------------------------------------------------------------------------------------------*/
+
+import { type Site } from "@azure/arm-appservice";
+import { type ExecuteActivityContext, type IActionContext, type ISubscriptionActionContext } from "@microsoft/vscode-azext-utils";
+
+export interface DeleteFunctionappWizardContext extends ISubscriptionActionContext, IActionContext, ExecuteActivityContext {
```
Comment (MicroFish91) [inline src/commands/deleteContainerizedFunctionApp/DeleteFunctionAppWizardContext.ts:9]: Think you forgot to remove the extra `IActionContext` here :)

**Review by MicroFish91 — APPROVED** [review]
Yay, ship it :D

**Comment by nturinski** [comment]
> Yay, ship it :D

You need to reapprove it then.

**Comment by motm32** [comment]
> > Yay, ship it :D
> 
> You need to reapprove it then.
Jokes on you
