### PR TITLE
Fix name validation for containerized function apps

### LINKED ISSUE #4011: There is no validation when entering a name with more than 32 characters for a containerized function app
**OS:** All
**Build Version:** 20240301.18
**Regression:** Not a Regression

**Repro Steps:**
1. Open a containerized function project in VS Code.
2. Right click on the Function App tree item and click on the command "Create Function App in Azure…" -> Click "Container Image" -> Enter a name which contains more than 32 characters for this function app.
3. Check whether there is a validation for the containerized function app name.

**Expect:**
There is a validation for the containerized function app name.

**Actual:**
There is no validation when entering a name with more than 32 characters for a containerized function app.
image

**More Info:**
An error occurs when creating a containerized function app named with more than 32 characters.
image

### PR DESCRIPTION
**Pull request by motm32**
Fixes #4011. 

Need to merge and release this appservice PR first.

### CODE REVIEW

File: src/tree/SubscriptionTreeItem.ts [hunk 1]
```diff
@@ -117,7 +117,7 @@ export class SubscriptionTreeItem extends SubscriptionTreeItemBase {
         await detectDockerfile(context);
 
         if (context.dockerfilePath) {
-            promptSteps.push(new SiteNameStep("containerizedfunctionApp"));
+            promptSteps.push(new SiteNameStep("containerizedFunctionApp"));
```
Comment (nturinski) [inline src/tree/SubscriptionTreeItem.ts:120]: I feel like it's more stylish to just use a ternary here
`promptSteps.push(new SiteNameStep(context.dockerfilePath  ? "containerizedFunctionApp" : "functionApp"));`

**Review by nturinski — APPROVED** [review]
