### PR TITLE
Fix multi-root support for downloading remote app settings and debugging

### LINKED ISSUE #3452: [Question]: Download remote settings for multiple functions in a workspace
Hi,

I had a question in regards to downloading remote settings for a function app.

My workspace contains multiple function apps.
I am able to deploy, test it, it all seems to work fine.

But when I try to download remote settings, it will prompt if `local.settings.json` doesn't exist for my first function app.
But if I try to select another function app and download it, I no longer have the prompt to select the target folder/app to download it to. It always overwrites the first one.

How do I force it to ask me every time what app to download the remote settings for?

Hope you can help, thanks!

Here is a screenshot of what I mean:

image

### PR DESCRIPTION
**Pull request by MicroFish91**
Fixes #3452 

This fixes both the downloading of remote app settings and local debugging for multi-root projects.

For the debug configuration fix, I changed this:

image
 to instead be tested with a RegExp.

Reason being, with multi-root, since the `preLaunchTask` config for projects that aren't the first one usually have a port assignment as part of the string, they will not match exactly the string `func: host start`.  Because of this, the local projects that come later were skipping `preDebugValidate`.  This should prevent them from being skipped now.

As per the wiki:
image

### CODE REVIEW

File: src/debug/FuncDebugProviderBase.ts [hunk 1]
```diff
@@ -46,7 +46,7 @@ export abstract class FuncDebugProviderBase implements DebugConfigurationProvide
             context.telemetry.suppressIfSuccessful = true;
 
             this._debugPorts.set(folder, <number | undefined>debugConfiguration.port);
-            if (debugConfiguration.preLaunchTask === hostStartTaskName) {
+            if (hostStartTaskNameRegExp.test(debugConfiguration.preLaunchTask)) {
```
Comment (nturinski) [inline src/debug/FuncDebugProviderBase.ts:49]: I'm okay with this change, but I don't think people should have been changing the name of their `preLaunchTask` to include the port. Where did you see that this was an issue? I didn't notice it skimming through the original issue.

**Review by nturinski — APPROVED** [review]

File: src/debug/FuncDebugProviderBase.ts (hunk 1 above)
Comment (MicroFish91) [reply src/debug/FuncDebugProviderBase.ts:49]: User mentioned: 

`The issue is only with the local.settings.json, it only seems to look for/pick the local.settings.json file of the first function app in the list.`

When I started digging into the screenshot and testing out the different configs, I stumbled across this as the likely culprit.
