### PR TITLE
Make function.json parsing less strict

### LINKED ISSUE #386: BUG: Failed to parse function.json: Expected "bindings" element of type "Array".
If you have a functions.json with a bindings:[] (empty), you receive this message and the plugin doesn't work properly.

Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to parse function.json: Expected "bindings" element of type "Array".

Version: 0.9.0
OS: win32

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**
Fixes #386

### CODE REVIEW

**Comment by EricJizbaMSFT** [comment]
ping

File: src/FunctionConfig.ts [hunk 1]
```diff
@@ -94,4 +98,20 @@ export class FunctionConfig {
...
         }
     }
+
+    public get inBinding(): IFunctionBinding {
+        if (!this._inBinding) {
+            throw this._noInBindingError;
+        } else {
+            return this._inBinding;
+        }
+    }
```
Comment (PrashanthCorp) [inline src/FunctionConfig.ts]: Is this primarily for the tests below? I see no mention of `this.inBinding` in this file. 
I'm mainly confused between the `const inBinding`  in the diff, and the above getter function.

File: src/FunctionConfig.ts [hunk 2]
```diff
@@ -55,31 +57,33 @@ export class FunctionConfig {
...
+                            this._inBindingType = this._inBinding.type;
+                            if (this._inBinding.type.toLowerCase() === 'httptrigger') {
+                                this.isHttpTrigger = true;
+                                if (this._inBinding.authLevel) {
+                                    const authLevel: HttpAuthLevel | undefined = <HttpAuthLevel>HttpAuthLevel[this._inBinding.authLevel.toLowerCase()];
+                                    if (authLevel === undefined) {
+                                        errMessage = localize('unrecognizedAuthLevel', 'Unrecognized auth level "{0}".', this._inBinding.authLevel);
+                                    } else {
+                                        this.authLevel = authLevel;
+                                    }
```
Comment (PrashanthCorp) [inline src/FunctionConfig.ts]: It feels like `authLevel` has a union type just for the error handling, which can be handled by checking if the key `this._inBinding.authLevel.toLowerCase()` is in HttpAuthLevel. 
This is just personal preference, feel free to ignore. :)

File: src/FunctionConfig.ts [hunk 3]
```diff
@@ -55,31 +57,33 @@ export class FunctionConfig {
...
+                    if (this._inBinding) {
+                        if (!this._inBinding.type) {
+                            errMessage = localize('inBindingTypeError', 'The binding with direction "in" must have a type.');
+                        } else {
+                            this._inBindingType = this._inBinding.type;
+                            if (this._inBinding.type.toLowerCase() === 'httptrigger') {
+                                this.isHttpTrigger = true;
+                                if (this._inBinding.authLevel) {
+                                    const authLevel: HttpAuthLevel | undefined = <HttpAuthLevel>HttpAuthLevel[this._inBinding.authLevel.toLowerCase()];
+                                    if (authLevel === undefined) {
```
Comment (PrashanthCorp) [inline src/FunctionConfig.ts]: Is `this.authLevel = null` a valid use case that shouldn't throw an error?

Comment (EricJizbaMSFT) [reply src/FunctionConfig.ts]: In this repo we almost always use 'undefined' and ignore 'null'. We can do that without too much worry since strictNullChecks is turned on

File: src/FunctionConfig.ts (hunk 1 above)
Comment (EricJizbaMSFT) [reply src/FunctionConfig.ts]: inBinding is a public member and is used outside this file. Before this change, we required it to be defined. Now, we don't require it to be defined _unless you try to access it_. This is because sometimes the code uses other parts of TemplateData and doesn't really need inBinding

File: src/FunctionConfig.ts [hunk 4]
```diff
@@ -55,31 +57,33 @@ export class FunctionConfig {
...
-                                    this.authLevel = authLevel;
+                    if (this._inBinding) {
+                        if (!this._inBinding.type) {
+                            errMessage = localize('inBindingTypeError', 'The binding with direction "in" must have a type.');
+                        } else {
+                            this._inBindingType = this._inBinding.type;
+                            if (this._inBinding.type.toLowerCase() === 'httptrigger') {
+                                this.isHttpTrigger = true;
+                                if (this._inBinding.authLevel) {
+                                    const authLevel: HttpAuthLevel | undefined = <HttpAuthLevel>HttpAuthLevel[this._inBinding.authLevel.toLowerCase()];
```
Comment (nturinski) [inline src/FunctionConfig.ts]: Any reason not to just set this.authLevel directly?  It'll be undefined if HttpAuthLevel is undefined anyway, right?

Comment (EricJizbaMSFT) [reply src/FunctionConfig.ts]: I'm pretty sure I did it this way for tslint reasons. Since 'this.authLevel' is of type 'HttpAuthLevel', tslint doesn't think I should be checking `if (this.authLevel === undefined)`
