### PR TITLE
Fix context menus

### LINKED ISSUE #3140: There are two extra actions in "Deployments" context menu after installing App Service extension unified build
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Service Extension Build Version:** 20220421.6 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Not a regression

**Repro Steps:**
1. Expand a Function App node in Azure Resources view.
2. Configure deployment source is None.
3. Right click the "Deployments" node to open its context menu.
4. Check whether there is no extra action in the context menu.

**Expect:**
There is no extra action in the context menu.
image

**Actual:**
There are two extra actions in the context menu.
image

### PR DESCRIPTION
**Pull request by alexweininger**
Fixes #3140 #3139

### CODE REVIEW

File: src/tree/ResolvedFunctionAppResource.ts [hunk 1]
```diff
@@ -190,12 +190,24 @@ export class ResolvedFunctionAppResource implements ResolvedAppResourceBase {
         const sourceControl: SiteSourceControl = await client.getSourceControl();
         const proxyTree: SlotTreeItem = this as unknown as SlotTreeItem;
 
-        this.deploymentsNode = new DeploymentsTreeItem(proxyTree, this.site, siteConfig, sourceControl);
+        this.deploymentsNode = new DeploymentsTreeItem(proxyTree, {
+            site: this.site,
+            siteConfig,
+            sourceControl,
+            contextValuesToAdd: ['azureFunctions']
```
Comment (nturinski) [inline src/tree/ResolvedFunctionAppResource.ts:197]: I think it makes sense to either use `azureFunctions` everywhere in this repo or `azFunc`.  Mixing and matching could get confusing.

Comment (alexweininger) [reply src/tree/ResolvedFunctionAppResource.ts]: Ok I switched them all to `azFunc`. I'd prefer `azureFunctions`, but there is already a lot of usages of `azFunc` and I'd rather not introduce (more) new bugs.

File: src/commands/openInPortal.ts [hunk 2]
```diff
@@ -13,5 +13,5 @@ export async function openInPortal(context: IActionContext, node?: AzExtTreeItem
         node = await ext.rgApi.tree.showTreeItemPicker<AzExtTreeItem>(new RegExp(ResolvedFunctionAppResource.productionContextValue), context);
     }
 
-    await uiOpenInPortal(node, node.fullId);
+    await uiOpenInPortal(node, `${nonNullProp(node, 'parent').parent?.id}/Deployments/${nonNullProp(node, 'id')}`);
```
Comment (nturinski) [inline src/commands/openInPortal.ts:16]: What's up with this? Doesn't this only work for very specific tree nodes?

Comment (alexweininger) [reply src/commands/openInPortal.ts:16]: The Functions open in portal command is now only used for deployment tree items, we could rename the command to make that more clear.

Comment (nturinski) [reply src/commands/openInPortal.ts:16]: Could you add a comment to that effect?  This would be super confusing.  Or maybe just change `openInPortal` to `openDeploymentInPortal`

**Review by nturinski — APPROVED** [review]
