### PR TITLE
Fix advanced creation for containerized function apps

### LINKED ISSUE #4002: Fail to create an advanced function app with "App Service Plan/Premium" hosting plan when a containerized function project opened in VS Code
**OS:** All
**Build Version:** 20240229.2
**Regression:** Not a Regression

**Repro Steps:**
1. Open a containerized function project in VS Code.
2. Right click on the Function App tree item and click on the command "Create Function App in Azure…(Advanced)" -> Click "Container Image" -> Enter a name -> Select a resource group -> Select a location -> Click "Premium/App Service Plan" hosting plan.
3. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
image

### PR DESCRIPTION
**Pull request by motm32**
The subwizard was running causing there still to be an error. Tested for both scenerios and they seem to work properly for me. 

Fixes #4002

### CODE REVIEW

File: src/commands/createFunctionApp/FunctionAppHostingPlanStep.ts [hunk 1]
```diff
@@ -27,10 +27,13 @@ export class FunctionAppHostingPlanStep extends AzureWizardPromptStep<IFunctionA
     }
 
     public shouldPrompt(context: IFunctionAppWizardContext): boolean {
-        return context.useConsumptionPlan === undefined || context.dockerfilePath !== undefined;
+        return context.useConsumptionPlan === undefined && context.dockerfilePath === undefined;
     }
 
     public async getSubWizard(_context: IFunctionAppWizardContext): Promise<IWizardOptions<IFunctionAppWizardContext> | undefined> {
+        if (_context.dockerfilePath) {
```
Comment (nturinski) [inline src/commands/createFunctionApp/FunctionAppHostingPlanStep.ts:34]: nit: Remove the _ from context. That's used by TypeScript to indicate an unused parameter, but since you're using it now, it doesn't make much sense.

**Review by nturinski — APPROVED** [review]
