### PR TITLE
Include func extensions install in Run Functions Host task

### LINKED ISSUE #584: Python projects need to run `func extensions install` before debugging
I see this for blob triggers unless I run `func extensions install`
```
[9/12/18 10:45:53 PM] The following 1 functions are in error:
[9/12/18 10:45:53 PM] BlobTriggerPython: The binding type(s) 'blobTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
```

@asavaritayal is this right? Should we be running `func extensions install`?

### PR DESCRIPTION
**Pull request by nturinski**
Fixes #584

### CODE REVIEW

File: src/commands/createNewProject/PythonProjectCreator.ts [hunk 1]
```diff
@@ -65,13 +65,13 @@ export class PythonProjectCreator extends ScriptProjectCreatorBase {
                     type: 'shell',
                     dependsOn: 'build',
```
Comment (EricJizbaMSFT) [inline src/commands/createNewProject/PythonProjectCreator.ts]: Can you remove this build thing since we decided it probs doesn't do anything
