### PR TITLE
Fix executing remote function

### LINKED ISSUE #3787: Unexpected status code: 401 when executing azure functions from vscode
Does this occur consistently? Yes
Repro steps:

1. When I manually try to invoke my deployed azure functions via vscode Azure extension, I simply gets this error and the function in not invoked. The error occurs instantly and happens for all of my azure functions

Action: azureFunctions.executeFunction
Error type: 401
Error Message: Unexpected status code: 401

Version: 1.12.2
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.80.2
Language: en

<details>
<summary>Call Stack</summary>

```
StatusCodePolicy.<anonymous> extension.bundle.js:2:3698275
fulfilled extension.bundle.js:2:3693254
```

</details>

### PR DESCRIPTION
**Pull request by alexweininger**
Fixes #3787

### CODE REVIEW

**Review by nturinski — APPROVED** [review]

File: src/commands/executeFunction.ts [hunk 1]
```diff
@@ -73,7 +73,7 @@ export async function executeFunction(context: IActionContext, node?: FunctionTr
             'Content-Type': 'application/json',
         });
         if (client) {
-            headers['x-functions-key'] = (await client.listHostKeys()).masterKey;
+            headers.set('x-functions-key', (await client.listHostKeys()).masterKey ?? '');
```
Comment (nturinski) [inline src/commands/executeFunction.ts:76]: This is the same command that I was having issues with while testing log streaming btw. I have a feeling something is going on with that API and it's down again (regarding the customer issue)

Comment (alexweininger) [reply src/commands/executeFunction.ts:76]: I was able to repro and verify that this fixed it.

Comment (nturinski) [reply src/commands/executeFunction.ts:76]: What authority was your function though? If it was anonymous, you don't need a master key, but I think you would if it's function or admin.
