### PR TITLE
Fix range error when creating new function app

### LINKED ISSUE #480: Fail to create function apps with error
Repro steps:
1. Right click the applied subscription and select 'Create Function App in Azure...'.
2. Check whether there is an error or not.

Expect:
There is no error.

Actual:
Pop up an error.
error

More Info:
This issue also reproduces on Mac and Linux.

Action: azureFunctions.createFunctionApp
Error type: RangeError
Error Message: {}

Version: 0.10.0
OS: win32

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**
Fixes #480

I figured since it was described as an enum [in package.json](https://github.com/Microsoft/vscode-azurefunctions/blob/master/package.json#L518) that it would return undefined, but turns out it returns an empty string.

@StephenWeatherford feel free to say "I told you so" since you're always advocating for `!foo` instead of `foo === undefined` 😂😂😂 I've been doing this because of the weird edge case where a valid enum value can be `0`, but that argument feels less and less worth it

### CODE REVIEW

**Comment by StephenWeatherford** [comment]
:-)

File: src/templates/DotnetTemplateRetriever.ts [hunk 1]
```diff
@@ -80,7 +81,7 @@ export function getDotnetVerifiedTemplateIds(runtime: string): string[] {
             case ProjectRuntime.beta:
                 return `${id}.2.x`;
             default:
-                throw new RangeError();
+                throw new RangeError(localize('invalidRuntime', 'Invalid runtime "{0}".', runtime));
```
Comment (StephenWeatherford) [inline src/templates/DotnetTemplateRetriever.ts]: Does localize handle it if runtime is undefined?  Maybe consider String(runtime)

File: src/tree/FunctionAppProvider.ts [hunk 2]
```diff
@@ -68,22 +68,22 @@ export class FunctionAppProvider implements IChildProvider {
 
 async function getDefaultRuntime(actionContext: IActionContext): Promise<ProjectRuntime> {
     // Try to get VS Code setting for runtime (aka if they have a project open)
-    let runtime: ProjectRuntime | undefined = getFuncExtensionSetting(projectRuntimeSetting);
+    let runtime: string | undefined = getFuncExtensionSetting(projectRuntimeSetting);
     actionContext.properties.runtimeSource = 'VSCodeSetting';
 
-    if (runtime === undefined) {
+    if (!runtime) {
```
Comment (PrashanthCorp) [inline src/tree/FunctionAppProvider.ts]: Is this the same behavior you intend to have for 0, null and other false-y values?

File: src/templates/DotnetTemplateRetriever.ts (hunk 1 above)
Comment (EricJizbaMSFT) [reply src/templates/DotnetTemplateRetriever.ts]: Yeah it's handled

File: src/tree/FunctionAppProvider.ts (hunk 2 above)
Comment (EricJizbaMSFT) [reply src/tree/FunctionAppProvider.ts]: Yep
