### PR TITLE
Remove containerized function apps from deploy quick pick 

### LINKED ISSUE #4160: Deploy to Azure (Function App) fails for a function containerized project
Currently Deploy to Azure operation  takes in user sub details and target function app name and just hangs. It  does not throw any error or anything . this is not a good experience for end customers as it does not provide any guidance /message on next set of actions user is expected to take. It just hangs in there.

### PR DESCRIPTION
**Pull request by motm32**
Fixes #4160

### CODE REVIEW

File: src/commands/deploy/FunctionAppListStep.ts [hunk 1]
```diff
@@ -26,7 +26,7 @@ export class FunctionAppListStep extends AzureWizardPromptStep<IFuncDeployContex
     private async getPicks(context: IFuncDeployContext): Promise<IAzureQuickPickItem<Site | undefined>[]> {
         const client = await createWebSiteClient([context, createSubscriptionContext(nonNullProp(context, 'subscription'))]);
         const sites = (await uiUtils.listAllIterator(client.webApps.list()));
-        const qp: IAzureQuickPickItem<Site | undefined>[] = sites.filter(s => !!s.kind?.includes('functionapp')).map(fa => {
+        const qp: IAzureQuickPickItem<Site | undefined>[] = sites.filter(s => !(s.kind?.includes('container')) && !!s.kind?.includes('functionapp')).map(fa => {
```
Comment (alexweininger) [inline src/commands/deploy/FunctionAppListStep.ts:29]:
```suggestion
        const qp: IAzureQuickPickItem<Site | undefined>[] = sites.filter(s => !s.kind?.includes('container') && !!s.kind?.includes('functionapp')).map(fa => {
```

Are those parens actually needed?

Comment (motm32) [reply src/commands/deploy/FunctionAppListStep.ts:29]: No it just made more sense to me that way but I can remove them

**Review by alexweininger — APPROVED** [review]
