### PR TITLE
Fix "+ Create new function app" error while deploying 

### LINKED ISSUE #4175: The error is not clear when executing deploying command for a containerized function app
**OS:** All
**Build Version:** v1.15.1-alpha.0
**Regression:** Not a Regression

**Repro Steps:**
1. Create and open a containerized function project in VS Code.
2. F1 -> Select "Azure Functions: Deploy to Azure..." -> Select "+ Create new function app" -> Select "Container Image" in the prompted dialog and follow the next steps to create a containerized function app to deploy.
3. Check whether a clear error occurs.

**Expect:**
A clear error occurs, such as "Deploy action is not supported on containerized function app".

**Actual:**
Succeed to create a containerized function app and an error occurs, the error is not clear.
image

### PR DESCRIPTION
**Pull request by motm32**
Fixes #4175 

Needed to add the `ResolvedContainerizedFunctionAppResource` being created when containerized function apps are being created through the deploy path. This is set up similarly to how it is done in `SubscriptionTreeItem`.

### CODE REVIEW

File: src/commands/deploy/getOrCreateFunctionApp.ts [hunk 1]
```diff
@@ -31,10 +32,16 @@ export async function getOrCreateFunctionApp(context: IFuncDeployContext & Parti
         context.activityTitle = localize('functionAppCreateActivityTitle', 'Create Function App "{0}"', nonNullProp(context, 'newSiteName'))
         await wizard.execute();
 
-        const resolved = new ResolvedFunctionAppResource(context as ISubscriptionContext, nonNullProp(context, 'site'));
+        if (context.dockerfilePath) {
+            const resolved = new ResolvedContainerizedFunctionAppResource(context as ISubscriptionContext, nonNullProp(context, 'site'))
+            node = await ext.rgApi.tree.findTreeItem(resolved.id, context);
```
Comment (nturinski) [inline src/commands/deploy/getOrCreateFunctionApp.ts:37]: nit: You only need to set node once after the if/else. 

You could also do a ternary for `context.dockerfilePath ? new Resolve...`

**Review by nturinski — APPROVED** [review]
