### PR TITLE
Replace showTreeItemPicker with pickAppResource

### LINKED ISSUE #3135: The new created function app is not focused after clicking "Click to view resource" from the "AZURE: ACTIVITYLOG" window
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure Function Extension build Version:** 20220421.8 (unified)
**Regression:** Not a Regression 

**Repro Steps:**
1. Create a new function app.
2. Navigate to the "AZURE: ACTIVITYLOG" window -> Expand the log -> Click "Click to view resource".
3. Check whether the new created function app is focused or not.

**Expect:**
The new created function app is focused.

**Actual:**
The new created function app is not focused.

### PR DESCRIPTION
**Pull request by alexweininger**
Fixes #3135 and #3132

### CODE REVIEW

File: src/commands/addBinding/addBinding.ts [hunk 1]
```diff
@@ -36,7 +36,10 @@ export async function addBinding(context: IActionContext, data: Uri | LocalFunct
     } else {
         if (!data) {
             const noItemFoundErrorMessage: string = localize('noLocalProject', 'No matching functions found. C# and Java projects do not support this operation.');
-            data = await ext.rgApi.tree.showTreeItemPicker<LocalFunctionTreeItem>(/Local;ReadWrite;Function;/i, { ...context, noItemFoundErrorMessage });
+            data = await ext.rgApi.pickAppResource<LocalFunctionTreeItem>({ ...context, noItemFoundErrorMessage }, {
```
Comment (nturinski) [inline src/commands/addBinding/addBinding.ts:39]: This is going to be in the workspaceProvider, so don't think that this will work.  Since we don't change the context value in the workspace, should be able to just do `ext.rgApi.workspaceTree.showTreeItemPicker`

File: src/commands/browseWebsite.ts [hunk 2]
```diff
@@ -4,14 +4,18 @@
...
 import { ResolvedFunctionAppResource } from '../tree/ResolvedFunctionAppResource';
 import { SlotTreeItem } from '../tree/SlotTreeItem';
 import { openUrl } from '../utils/openUrl';
 
 export async function browseWebsite(context: IActionContext, node?: SlotTreeItem): Promise<void> {
     if (!node) {
-        node = await ext.rgApi.tree.showTreeItemPicker<SlotTreeItem>(new RegExp(ResolvedFunctionAppResource.productionContextValue), context);
+        node = await ext.rgApi.pickAppResource<SlotTreeItem>(context, {
+            filter: functionFilter,
+            expectedChildContextValue: new RegExp(ResolvedFunctionAppResource.productionContextValue)
```
Comment (nturinski) [inline src/commands/browseWebsite.ts:17]: Do you need the `expectedChildContextValue`?  Isn't the `productionContextValue` the `AppResource` itself?

File: src/commands/viewProperties.ts [hunk 3]
```diff
@@ -14,7 +15,10 @@ import { SlotTreeItem } from '../tree/SlotTreeItem';
 
 export async function viewProperties(context: IActionContext, node?: SlotTreeItem | RemoteFunctionTreeItem | LocalFunctionTreeItem): Promise<void> {
     if (!node) {
-        node = await ext.rgApi.tree.showTreeItemPicker<SlotTreeItem>(new RegExp(ResolvedFunctionAppResource.productionContextValue), context);
+        node = await ext.rgApi.pickAppResource<SlotTreeItem>(context, {
```
Comment (nturinski) [inline src/commands/viewProperties.ts:18]: We're getting rid of this command in favor of RG, right?

File: src/commands/swapSlot.ts [hunk 4]
```diff
@@ -5,13 +5,17 @@
...
 import { ext } from '../extensionVariables';
 import { ResolvedFunctionAppResource } from '../tree/ResolvedFunctionAppResource';
 import { SlotTreeItem } from '../tree/SlotTreeItem';
 
 export async function swapSlot(context: IActionContext, sourceSlotNode?: SlotTreeItem): Promise<void> {
     if (!sourceSlotNode) {
-        sourceSlotNode = await ext.rgApi.tree.showTreeItemPicker<SlotTreeItem>(ResolvedFunctionAppResource.pickSlotContextValue, { ...context, suppressCreatePick: true });
+        sourceSlotNode = await ext.rgApi.pickAppResource<SlotTreeItem>({ ...context, suppressCreatePick: true }, {
+            filter: functionFilter,
+            expectedChildContextValue: new RegExp(ResolvedFunctionAppResource.productionContextValue)
```
Comment (nturinski) [inline src/commands/swapSlot.ts:17]: I think that this should be `ResolvedFunctionAppResource.slotContextValue`

File: src/commands/viewProperties.ts (hunk 3 above)
Comment (alexweininger) [reply src/commands/viewProperties.ts:18]: Yeah I was going to do that afterwards

File: src/commands/browseWebsite.ts (hunk 2 above)
Comment (alexweininger) [reply src/commands/browseWebsite.ts:17]: This unintentionally forces it to get resolved. And it doesn't behave weirdly. If we leave it out then we have to manually resolve it after calling `pickAppResource`.

File: src/commands/viewProperties.ts (hunk 3 above)
Comment (alexweininger) [reply src/commands/viewProperties.ts:18]: So actually, the view properties command needs to still exist, but just not on the app resource. So it should never show up in the tree.
